# Generated by Django 4.0.1 on 2022-01-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.CharField(blank=True, default='marti', max_length=100),
        ),
    ]
