# Generated by Django 4.0.1 on 2022-01-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
